services:
  maestro:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - maestro-dev:/app
    environment:
      REPO_URL: https://dev.azure.com/ClearAlanInc/ClearAlan%20Inc/_git/Maestro Connect
      BRANCH: master
    env_file:
      - path: .env
        required: false
    restart: "no"

volumes:
  maestro-dev:
