import { port, ports, trunkPort } from "./_helpers";
import type { DeviceTemplate } from "../types";

export const templates: DeviceTemplate[] = [
  // Control Processors
  // Crestron CP4N — Control Processor
  {
    id: "c0a80101-0038-4000-8000-000000000056",
    deviceType: "control-processor",
    label: "Crestron CP4N",
    manufacturer: "Crestron",
    modelNumber: "CP4N",
    referenceUrl: "https://www.crestron.com/Products/Catalog/Control-and-Management/Control-System/Rack-Mount/CP4N",
    searchTerms: ["crestron", "control", "processor", "automation", "cp4"],
    powerDrawW: 50, // typical
    heightMm: 44,
    widthMm: 483,
    depthMm: 167,
    weightKg: 1.4,
    ports: [
      port("LAN", "ethernet", "bidirectional"),
      port("Control Subnet", "ethernet", "bidirectional"),
      port("COM (RS-232)", "serial", "bidirectional"),
      port("IR/Serial", "serial", "output"),
      port("Relay", "gpio", "output"),
      port("Versiport I/O", "gpio", "bidirectional"),
      port("Cresnet", "serial", "bidirectional"),
      port("USB", "usb", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  // Crestron RMC4 — 4-Series Room Media Controller (PoE powered, IFE micro form factor)
  {
    id: "c0a80101-030c-4000-8000-000000000734",
    deviceType: "control-processor",
    label: "Crestron RMC4",
    manufacturer: "Crestron",
    modelNumber: "RMC4",
    referenceUrl: "https://www.crestron.com/Products/Catalog/Control-and-Management/Control-System/Wall-Mount/RMC4",
    searchTerms: ["crestron", "control", "processor", "automation", "rmc4", "4-series", "room", "media", "controller", "poe"],
    powerDrawW: 6.5,
    poeDrawW: 12.95, // 802.3at Type 1 Class 0 PD allocation; actual consumption 6.5 W
    thermalBtuh: 22,
    heightMm: 34,
    widthMm: 128,
    depthMm: 73,
    weightKg: 0.18,
    rackForm: "shelf-only",
    ports: [
      port("LAN (PoE)", "ethernet", "bidirectional"),
      port("NET (Cresnet, data only)", "cresnet", "bidirectional"),
      port("COM (RS-232/422/485)", "serial", "bidirectional", "phoenix"),
      // IR ports also do 1-way TTL/RS-232 serial, so the signal is inherited per design
      { ...port("IR/Serial 1", "custom", "output", "terminal-block"), inheritsSignal: true },
      { ...port("IR/Serial 2", "custom", "output", "terminal-block"), inheritsSignal: true },
      port("Digital In 1", "gpio", "input"),
      port("Digital In 2", "gpio", "input"),
      port("Relay 1", "contact-closure", "output"),
      port("Relay 2", "contact-closure", "output"),
      port("USB OTG", "usb", "bidirectional", "usb-micro"),
    ],
  },
  // Crestron MC4 — 4-Series Control System (PoE powered, surface/1RU rack mount)
  {
    id: "c0a80101-030d-4000-8000-000000000735",
    deviceType: "control-processor",
    label: "Crestron MC4",
    manufacturer: "Crestron",
    modelNumber: "MC4",
    referenceUrl: "https://www.crestron.com/Products/Catalog/Control-and-Management/Control-System/Wall-Mount/MC4",
    searchTerms: ["crestron", "control", "processor", "automation", "mc4", "4-series", "infinet", "poe"],
    powerDrawW: 7,
    poeDrawW: 12.95, // 802.3at Type 1 Class 0 PD allocation; actual consumption 7 W typical
    thermalBtuh: 24,
    heightMm: 27,
    widthMm: 258,
    depthMm: 130,
    weightKg: 0.45,
    rackForm: "full", // 1RU rack ears included
    ports: [
      port("LAN (PoE, GbE)", "ethernet", "bidirectional"),
      port("CRESNET", "cresnet", "bidirectional"),
      port("COM (RS-232)", "serial", "bidirectional", "phoenix"),
      { ...port("IR/Serial 1", "custom", "output", "terminal-block"), inheritsSignal: true },
      { ...port("IR/Serial 2", "custom", "output", "terminal-block"), inheritsSignal: true },
      { ...port("IR/Serial 3", "custom", "output", "terminal-block"), inheritsSignal: true },
      { ...port("IR/Serial 4", "custom", "output", "terminal-block"), inheritsSignal: true },
      port("IR In", "ir", "input", "trs-eighth"),
      port("Versiport 1", "gpio", "bidirectional"),
      port("Versiport 2", "gpio", "bidirectional"),
      port("Relay 1", "contact-closure", "output"),
      port("Relay 2", "contact-closure", "output"),
      port("USB (Host)", "usb", "bidirectional", "usb-a"),
    ],
  },
  // Crestron DIN-AP4 — 4-Series DIN Rail Control System
  {
    id: "c0a80101-030e-4000-8000-000000000736",
    deviceType: "control-processor",
    label: "Crestron DIN-AP4",
    manufacturer: "Crestron",
    modelNumber: "DIN-AP4",
    referenceUrl: "https://www.crestron.com/Products/Catalog/Control-and-Management/Control-System/DIN-Rail/DIN-AP4",
    searchTerms: ["crestron", "control", "processor", "automation", "din-ap4", "4-series", "din", "rail"],
    powerDrawW: 9.7,
    poeDrawW: 12.95, // 802.3at Type 1 Class 0 PD allocation; alternatively 24VDC power pack
    thermalBtuh: 33,
    voltage: "24VDC or PoE",
    heightMm: 91,
    widthMm: 161,
    depthMm: 58,
    weightKg: 0.28,
    rackForm: "shelf-only", // DIN rail mount, 9 DIN modules wide
    ports: [
      port("LAN (PoE)", "ethernet", "bidirectional"),
      port("NET 1 (Cresnet)", "cresnet", "bidirectional"),
      port("NET 2 (Cresnet)", "cresnet", "bidirectional"),
      port("COM 1 (RS-232/422/485)", "serial", "bidirectional", "phoenix"),
      port("COM 2 (RS-232/422/485)", "serial", "bidirectional", "phoenix"),
      { ...port("IR/Serial 1", "custom", "output", "terminal-block"), inheritsSignal: true },
      { ...port("IR/Serial 2", "custom", "output", "terminal-block"), inheritsSignal: true },
      { ...port("IR/Serial 3", "custom", "output", "terminal-block"), inheritsSignal: true },
      { ...port("IR/Serial 4", "custom", "output", "terminal-block"), inheritsSignal: true },
      port("Relay 1", "contact-closure", "output"),
      port("Relay 2", "contact-closure", "output"),
      port("Relay 3", "contact-closure", "output"),
      port("Relay 4", "contact-closure", "output"),
      port("Versiport I/O 1", "gpio", "bidirectional"),
      port("Versiport I/O 2", "gpio", "bidirectional"),
      port("Versiport I/O 3", "gpio", "bidirectional"),
      port("Versiport I/O 4", "gpio", "bidirectional"),
      port("Versiport I/O 5", "gpio", "bidirectional"),
      port("Versiport I/O 6", "gpio", "bidirectional"),
      port("Versiport I/O 7", "gpio", "bidirectional"),
      port("Versiport I/O 8", "gpio", "bidirectional"),
      port("USB (Host)", "usb", "bidirectional", "usb-a"),
      port("Computer (Console)", "usb", "bidirectional", "usb-b"),
      port("DC Power (24V)", "power", "input", "terminal-block"),
    ],
  },
  // Crestron CEN-IO wired Ethernet I/O modules (PoE, IFE micro form factor)
  {
    id: "c0a80101-030f-4000-8000-000000000737",
    deviceType: "control-expansion",
    label: "Crestron CEN-IO-COM-102",
    manufacturer: "Crestron",
    modelNumber: "CEN-IO-COM-102",
    referenceUrl: "https://www.crestron.com/Products/Catalog/Control-and-Management/Control-System/Expansion-IO/CEN-IO-COM-102",
    searchTerms: ["crestron", "cen-io", "com", "serial", "expander", "ethernet", "module", "poe"],
    powerDrawW: 1.9,
    poeDrawW: 12.95, // 802.3at Type 1 Class 0 PD allocation; actual consumption 1.9 W
    thermalBtuh: 7,
    heightMm: 34,
    widthMm: 128,
    depthMm: 73,
    weightKg: 0.18,
    rackForm: "shelf-only",
    ports: [
      port("LAN (PoE)", "ethernet", "bidirectional"),
      port("COM 1 (RS-232)", "serial", "bidirectional", "phoenix"),
      port("COM 2 (RS-232)", "serial", "bidirectional", "phoenix"),
    ],
  },
  {
    id: "c0a80101-0310-4000-8000-000000000738",
    deviceType: "control-expansion",
    label: "Crestron CEN-IO-COM-202",
    manufacturer: "Crestron",
    modelNumber: "CEN-IO-COM-202",
    referenceUrl: "https://www.crestron.com/Products/Catalog/Control-and-Management/Control-System/Expansion-IO/CEN-IO-COM-202",
    searchTerms: ["crestron", "cen-io", "com", "serial", "expander", "wifi", "wireless", "module"],
    powerDrawW: 0.8,
    thermalBtuh: 2.7,
    voltage: "5VDC",
    heightMm: 34,
    widthMm: 128,
    depthMm: 73,
    weightKg: 0.18,
    rackForm: "shelf-only",
    ports: [
      port("Wi-Fi", "ethernet", "bidirectional", "wireless"),
      port("COM 1 (RS-232)", "serial", "bidirectional", "phoenix"),
      port("COM 2 (RS-232)", "serial", "bidirectional", "phoenix"),
      port("USB (Console)", "usb", "bidirectional", "usb-micro"),
      port("DC Power (5V)", "power", "input", "terminal-block"),
    ],
  },
  {
    id: "c0a80101-0311-4000-8000-000000000739",
    deviceType: "control-expansion",
    label: "Crestron CEN-IO-DIGIN-104",
    manufacturer: "Crestron",
    modelNumber: "CEN-IO-DIGIN-104",
    referenceUrl: "https://www.crestron.com/Products/Catalog/Control-and-Management/Control-System/Expansion-IO/CEN-IO-DIGIN-104",
    searchTerms: ["crestron", "cen-io", "digin", "digital", "input", "expander", "ethernet", "module", "poe"],
    powerDrawW: 1.8,
    poeDrawW: 12.95, // 802.3at Type 1 Class 0 PD allocation; actual consumption 1.8 W
    thermalBtuh: 7,
    heightMm: 34,
    widthMm: 128,
    depthMm: 73,
    weightKg: 0.18,
    rackForm: "shelf-only",
    ports: [
      port("LAN (PoE)", "ethernet", "bidirectional"),
      port("Digital In 1", "gpio", "input"),
      port("Digital In 2", "gpio", "input"),
      port("Digital In 3", "gpio", "input"),
      port("Digital In 4", "gpio", "input"),
    ],
  },
  {
    id: "c0a80101-0312-4000-8000-000000000740",
    deviceType: "control-expansion",
    label: "Crestron CEN-IO-DIGIN-204",
    manufacturer: "Crestron",
    modelNumber: "CEN-IO-DIGIN-204",
    referenceUrl: "https://www.crestron.com/Products/Catalog/Control-and-Management/Control-System/Expansion-IO/CEN-IO-DIGIN-204",
    searchTerms: ["crestron", "cen-io", "digin", "digital", "input", "expander", "wifi", "wireless", "module"],
    powerDrawW: 0.7,
    thermalBtuh: 2.4,
    voltage: "5VDC",
    heightMm: 34,
    widthMm: 128,
    depthMm: 73,
    weightKg: 0.18,
    rackForm: "shelf-only",
    ports: [
      port("Wi-Fi", "ethernet", "bidirectional", "wireless"),
      port("Digital In 1", "gpio", "input"),
      port("Digital In 2", "gpio", "input"),
      port("Digital In 3", "gpio", "input"),
      port("Digital In 4", "gpio", "input"),
      port("USB (Console)", "usb", "bidirectional", "usb-micro"),
      port("DC Power (5V)", "power", "input", "terminal-block"),
    ],
  },
  {
    id: "c0a80101-0313-4000-8000-000000000741",
    deviceType: "control-expansion",
    label: "Crestron CEN-IO-IR-104",
    manufacturer: "Crestron",
    modelNumber: "CEN-IO-IR-104",
    referenceUrl: "https://www.crestron.com/Products/Catalog/Control-and-Management/Control-System/Expansion-IO/CEN-IO-IR-104",
    searchTerms: ["crestron", "cen-io", "ir", "infrared", "expander", "ethernet", "module", "poe"],
    powerDrawW: 2.3,
    poeDrawW: 12.95, // 802.3at Type 1 Class 0 PD allocation; actual consumption 2.3 W
    thermalBtuh: 8,
    heightMm: 34,
    widthMm: 128,
    depthMm: 73,
    weightKg: 0.18,
    rackForm: "shelf-only",
    ports: [
      port("LAN (PoE)", "ethernet", "bidirectional"),
      { ...port("IR/Serial 1", "custom", "output", "terminal-block"), inheritsSignal: true },
      { ...port("IR/Serial 2", "custom", "output", "terminal-block"), inheritsSignal: true },
      { ...port("IR/Serial 3", "custom", "output", "terminal-block"), inheritsSignal: true },
      { ...port("IR/Serial 4", "custom", "output", "terminal-block"), inheritsSignal: true },
    ],
  },
  {
    id: "c0a80101-0314-4000-8000-000000000742",
    deviceType: "control-expansion",
    label: "Crestron CEN-IO-IR-204",
    manufacturer: "Crestron",
    modelNumber: "CEN-IO-IR-204",
    referenceUrl: "https://www.crestron.com/Products/Catalog/Control-and-Management/Control-System/Expansion-IO/CEN-IO-IR-204",
    searchTerms: ["crestron", "cen-io", "ir", "infrared", "expander", "wifi", "wireless", "module"],
    powerDrawW: 1.1,
    thermalBtuh: 3.6,
    voltage: "5VDC",
    heightMm: 34,
    widthMm: 128,
    depthMm: 73,
    weightKg: 0.18,
    rackForm: "shelf-only",
    ports: [
      port("Wi-Fi", "ethernet", "bidirectional", "wireless"),
      { ...port("IR/Serial 1", "custom", "output", "terminal-block"), inheritsSignal: true },
      { ...port("IR/Serial 2", "custom", "output", "terminal-block"), inheritsSignal: true },
      { ...port("IR/Serial 3", "custom", "output", "terminal-block"), inheritsSignal: true },
      { ...port("IR/Serial 4", "custom", "output", "terminal-block"), inheritsSignal: true },
      port("USB (Console)", "usb", "bidirectional", "usb-micro"),
      port("DC Power (5V)", "power", "input", "terminal-block"),
    ],
  },
  // Crestron DGE-1000 — Digital Graphics Engine (drives TSD-2220 or third-party touch display)
  {
    id: "c0a80101-0315-4000-8000-000000000743",
    deviceType: "touch-controller",
    label: "Crestron DGE-1000",
    manufacturer: "Crestron",
    modelNumber: "DGE-1000",
    referenceUrl: "https://www.crestron.com/Products/Catalog/Control-and-Management/User-Interfaces/Graphics-Engine/DGE-1000",
    searchTerms: ["crestron", "dge", "graphics", "engine", "touchscreen", "html5", "controller"],
    powerDrawW: 14,
    poeDrawW: 25.5, // PoE+ Class 4 PD allocation; alternatively 24VDC power pack (sold separately)
    thermalBtuh: 47.8,
    voltage: "24VDC or PoE+",
    heightMm: 33,
    widthMm: 188,
    depthMm: 166,
    weightKg: 0.86,
    rackForm: "shelf-only",
    ports: [
      port("HDMI In", "hdmi", "input"),
      port("HDMI Out", "hdmi", "output"),
      port("LAN (PoE+, GbE)", "ethernet", "bidirectional"),
      port("COM (RS-232)", "serial", "bidirectional", "phoenix"),
      { ...port("IR/Serial", "custom", "output", "terminal-block"), inheritsSignal: true },
      port("Audio Out", "analog-audio", "output", "phoenix"),
      port("USB Host 1 (2.0)", "usb", "bidirectional", "usb-a"),
      port("USB Host 2 (3.0)", "usb", "bidirectional", "usb-a"),
      port("USB (Console)", "usb", "bidirectional", "usb-b"),
      port("DC Power (24V)", "power", "input", "barrel"),
    ],
  },
  // Crestron DM-DGE-200-C — Digital Graphics Engine with 4K DM 8G+ input
  {
    id: "c0a80101-0316-4000-8000-000000000744",
    deviceType: "touch-controller",
    label: "Crestron DM-DGE-200-C",
    manufacturer: "Crestron",
    modelNumber: "DM-DGE-200-C",
    referenceUrl: "https://www.crestron.com/Products/Catalog/Control-and-Management/User-Interfaces/Graphics-Engine/DM-DGE-200-C",
    searchTerms: ["crestron", "dge", "graphics", "engine", "touchscreen", "dm", "8g+", "smart", "controller"],
    powerDrawW: 24,
    poeBudgetW: 15.4, // PoDM PSE — supplies up to 15.4 W to one PoDM PD via the DM IN port
    thermalBtuh: 81.9,
    voltage: "24VDC",
    heightMm: 203,
    widthMm: 236,
    depthMm: 35,
    weightKg: 0.73,
    rackForm: "shelf-only",
    ports: [
      port("DM In (DM 8G+)", "hdbaset", "input", "rj45"),
      port("HDMI In", "hdmi", "input"),
      port("HDMI Out", "hdmi", "output"),
      port("LAN", "ethernet", "bidirectional"),
      port("COM (RS-232)", "serial", "bidirectional", "phoenix"),
      { ...port("IR/Serial 1", "custom", "output", "terminal-block"), inheritsSignal: true },
      { ...port("IR/Serial 2", "custom", "output", "terminal-block"), inheritsSignal: true },
      port("USB (Host)", "usb", "bidirectional", "usb-a"),
      port("USB (Console)", "usb", "bidirectional", "usb-micro"),
      port("DC Power (24V)", "power", "input", "barrel"),
    ],
  },
  // Crestron TS-880 / TS-1080 — tabletop touch screens (PoE+ or Wi-Fi)
  {
    id: "c0a80101-0317-4000-8000-000000000745",
    deviceType: "touch-screen",
    label: "Crestron TS-880",
    manufacturer: "Crestron",
    modelNumber: "TS-880",
    referenceUrl: "https://www.crestron.com/Products/Catalog/Control-and-Management/User-Interfaces/Touchscreen/TS-880-B",
    searchTerms: ["crestron", "touch", "screen", "tabletop", "ts-880", "ts-880-b", "ts-880-w", "8 inch", "poe"],
    powerDrawW: 12.9, // derived from 44 BTU/hr heat dissipation
    poeDrawW: 30, // requests 30 W (PoE+ Class 4) from 802.3at Type 2 PSE; 15.4 W from 802.3af (USB port disabled)
    thermalBtuh: 44,
    heightMm: 124,
    widthMm: 201,
    depthMm: 115,
    weightKg: 0.8,
    rackForm: "shelf-only",
    ports: [
      port("LAN (PoE+, GbE)", "ethernet", "bidirectional"),
      port("Wi-Fi", "ethernet", "bidirectional", "wireless"),
      port("USB-C", "usb", "bidirectional", "usb-c"),
    ],
  },
  {
    id: "c0a80101-0318-4000-8000-000000000746",
    deviceType: "touch-screen",
    label: "Crestron TS-1080",
    manufacturer: "Crestron",
    modelNumber: "TS-1080",
    referenceUrl: "https://www.crestron.com/Products/Catalog/Control-and-Management/User-Interfaces/Touchscreen/TS-1080-B",
    searchTerms: ["crestron", "touch", "screen", "tabletop", "ts-1080", "ts-1080-b", "ts-1080-w", "10 inch", "poe"],
    powerDrawW: 12.9, // derived from 44 BTU/hr heat dissipation
    poeDrawW: 30, // requests 30 W (PoE+ Class 4) from 802.3at Type 2 PSE; 15.4 W from 802.3af (USB port disabled)
    thermalBtuh: 44,
    heightMm: 151,
    widthMm: 246,
    depthMm: 115,
    weightKg: 1.01, // spec sheet lists 2.23 lb (464 g) — figures disagree; 2.23 lb = 1.01 kg used
    rackForm: "shelf-only",
    ports: [
      port("LAN (PoE+, GbE)", "ethernet", "bidirectional"),
      port("Wi-Fi", "ethernet", "bidirectional", "wireless"),
      port("USB-C", "usb", "bidirectional", "usb-c"),
    ],
  },
  // Crestron TST-1080 — wireless (Wi-Fi only) touch screen with table dock charger
  {
    id: "c0a80101-0319-4000-8000-000000000747",
    deviceType: "touch-screen",
    label: "Crestron TST-1080",
    manufacturer: "Crestron",
    modelNumber: "TST-1080",
    referenceUrl: "https://www.crestron.com/Products/Catalog/Control-and-Management/User-Interfaces/Wireless-Touchscreen/TST-1080",
    searchTerms: ["crestron", "touch", "screen", "wireless", "tst-1080", "10 inch", "wifi", "battery", "tablet"],
    powerDrawW: 6,
    thermalBtuh: 20.5,
    heightMm: 163,
    widthMm: 262,
    depthMm: 14,
    weightKg: 0.78,
    rackForm: "shelf-only",
    ports: [
      port("Wi-Fi", "ethernet", "bidirectional", "wireless"),
      port("USB-C (Charging)", "power", "input", "usb-c"),
    ],
  },
  // Tally Systems
  // BMD GPI and Tally Interface
  {
    id: "c0a80101-0039-4000-8000-000000000057",
    deviceType: "tally-system",
    label: "BMD GPI & Tally",
    manufacturer: "Blackmagic Design",
    modelNumber: "GPI and Tally Interface",
    referenceUrl: "https://www.blackmagicdesign.com/products/atemconstellation/techspecs/W-ATC-03",
    searchTerms: ["blackmagic", "tally", "gpi", "gpio", "indicator"],
    powerDrawW: 5, // typical
    heightMm: 65,
    widthMm: 145,
    depthMm: 139,
    weightKg: 0.4,
    ports: [
      port("Ethernet In", "ethernet", "bidirectional"),
      port("Ethernet Loop", "ethernet", "bidirectional"),
      trunkPort("GPI In", "gpio", "input", 8, "db25"),
      trunkPort("GPI Out", "gpio", "output", 8, "db25"),
      port("AC Power", "power", "input"),
    ],
  },
  // ── Misc ─────────────────────────────────────────────────────────
  {
    id: "c0a80101-00cf-4000-8000-000000000207",
    deviceType: "control-processor",
    label: "D'San Perfect Cue",
    manufacturer: "D'San",
    modelNumber: "Perfect Cue",
    referenceUrl: "https://dsanproducts.com/",
    searchTerms: ["dsan", "perfect cue", "speaker timer", "presentation"],
    powerDrawW: 10, // typical
    heightMm: 83,
    widthMm: 178,
    depthMm: 102,
    weightKg: 4.5,
    ports: [
      port("Ethernet", "ethernet", "bidirectional"),
      port("RS-232", "serial", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-00d0-4000-8000-000000000208",
    deviceType: "timecode-generator",
    label: "Brainstorm SR-112",
    manufacturer: "Brainstorm Electronics",
    modelNumber: "SR-112",
    referenceUrl: "https://www.brainstormtime.com/products/sr-112/",
    searchTerms: ["brainstorm", "sr-112", "timecode", "smpte", "ltc", "generator"],
    powerDrawW: 15, // typical
    heightMm: 44,
    widthMm: 483,
    depthMm: 206,
    ports: [
      port("LTC Out 1", "analog-audio", "output"),
      port("LTC Out 2", "analog-audio", "output"),
      port("Ref In", "genlock", "input"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("MIDI Out", "midi", "output", "din-5"),
      port("USB", "usb", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-00d1-4000-8000-000000000209",
    deviceType: "midi-device",
    label: "MIDI Merge 4x2",
    searchTerms: ["midi", "merge", "combiner"],
    powerDrawW: 5, // typical
    ports: [
      ...ports("MIDI In", "midi", "input", 4, "din-5"),
      port("MIDI Out 1", "midi", "output", "din-5"),
      port("MIDI Out 2", "midi", "output", "din-5"),
    ],
  },
  {
    id: "c0a80101-00d2-4000-8000-000000000210",
    deviceType: "midi-device",
    label: "MIDI Thru 1x4",
    searchTerms: ["midi", "thru", "splitter"],
    powerDrawW: 5, // typical
    ports: [
      port("MIDI In", "midi", "input", "din-5"),
      ...ports("MIDI Thru", "midi", "output", 4, "din-5"),
    ],
  },
  {
    id: "c0a80101-024b-4000-8000-000000000732",
    deviceType: "ptz-controller",
    label: "AIDA CCU-MINI",
    manufacturer: "AIDA Imaging",
    modelNumber: "CCU-MINI",
    referenceUrl: "https://aidaimaging.com/ccu-mini/",
    searchTerms: ["aida", "ccu-mini", "ptz", "controller", "visca", "joystick"],
    heightMm: 101.6,
    widthMm: 171.45,
    depthMm: 139.7,
    weightKg: 0.9,
    ports: [
      port("LAN (VISCA over IP)", "ethernet", "bidirectional"),
      port("RS-422 (VISCA)", "rs422", "bidirectional", "rj45"),
      port("RS-485 / RS-232", "rs485", "bidirectional", "phoenix"),
      port("DC Power (12V)", "power", "input", "barrel"),
    ],
  },
];
