import { port, ports } from "./_helpers";
import type { DeviceTemplate } from "../types";

export const templates: DeviceTemplate[] = [
  // NDI Encoder
  {
    id: "c0a80101-0012-4000-8000-000000000018",
    deviceType: "ndi-encoder",
    label: "NDI Encoder",
    powerDrawW: 15, // typical
    ports: [
      port("SDI In", "sdi", "input"),
      port("HDMI In", "hdmi", "input"),
      port("NDI Out", "ndi", "output"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  // NDI Decoder
  {
    id: "c0a80101-0013-4000-8000-000000000019",
    deviceType: "ndi-decoder",
    label: "NDI Decoder",
    powerDrawW: 15, // typical
    ports: [
      port("NDI In", "ndi", "input"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("SDI Out", "sdi", "output"),
      port("HDMI Out", "hdmi", "output"),
      port("AC Power", "power", "input"),
    ],
  },
  // Ethernet Switch (4-port)
  {
    id: "c0a80101-0025-4000-8000-000000000037",
    deviceType: "network-switch",
    label: "Ethernet Switch (4-port)",
    searchTerms: ["switch", "network", "poe"],
    powerDrawW: 15,
    poeBudgetW: 60,
    ports: [
      { ...port("Port 1", "ethernet", "bidirectional", undefined, false), linkSpeed: "1G" },
      { ...port("Port 2", "ethernet", "bidirectional", undefined, false), linkSpeed: "1G" },
      { ...port("Port 3", "ethernet", "bidirectional", undefined, false), linkSpeed: "1G" },
      { ...port("Port 4", "ethernet", "bidirectional", undefined, false), linkSpeed: "1G" },
      port("AC Power", "power", "input"),
    ],
  },
  // Ethernet Switch (8-port)
  {
    id: "c0a80101-0026-4000-8000-000000000038",
    deviceType: "network-switch",
    label: "Ethernet Switch (8-port)",
    searchTerms: ["switch", "network", "poe"],
    powerDrawW: 25,
    poeBudgetW: 120,
    ports: [
      { ...port("Port 1", "ethernet", "bidirectional", undefined, false), linkSpeed: "1G" },
      { ...port("Port 2", "ethernet", "bidirectional", undefined, false), linkSpeed: "1G" },
      { ...port("Port 3", "ethernet", "bidirectional", undefined, false), linkSpeed: "1G" },
      { ...port("Port 4", "ethernet", "bidirectional", undefined, false), linkSpeed: "1G" },
      { ...port("Port 5", "ethernet", "bidirectional", undefined, false), linkSpeed: "1G" },
      { ...port("Port 6", "ethernet", "bidirectional", undefined, false), linkSpeed: "1G" },
      { ...port("Port 7", "ethernet", "bidirectional", undefined, false), linkSpeed: "1G" },
      { ...port("Port 8", "ethernet", "bidirectional", undefined, false), linkSpeed: "1G" },
      port("AC Power", "power", "input"),
    ],
  },
  // Streaming Encoder
  // Teradek Prism Flex — Streaming Encoder/Decoder
  {
    id: "c0a80101-0033-4000-8000-000000000051",
    deviceType: "streaming-encoder",
    label: "Teradek Prism Flex",
    manufacturer: "Teradek",
    modelNumber: "Prism Flex",
    referenceUrl: "https://teradek.com/pages/prism-flex",
    searchTerms: ["teradek", "prism", "streaming", "encoder", "rtmp", "srt", "hevc"],
    powerDrawW: 30, // typical
    heightMm: 35,
    widthMm: 162,
    depthMm: 92,
    weightKg: 0.3,
    ports: [
      port("SDI In", "sdi", "input"),
      port("HDMI In", "hdmi", "input"),
      port("SDI Loop", "sdi", "output"),
      port("Ethernet 1", "ethernet", "bidirectional"),
      port("Ethernet 2", "ethernet", "bidirectional"),
      port("USB 1", "usb", "bidirectional"),
      port("USB 2", "usb", "bidirectional"),
      port("AC Power", "power", "input"),
    
      port("SDI Out", "sdi", "output"),
    
      port("HDMI Out", "hdmi", "output"),
    ],
  },
  // AV-over-IP
  // Crestron DM-NVX-351 — AV-over-IP Encoder/Decoder
  {
    id: "c0a80101-003a-4000-8000-000000000058",
    deviceType: "av-over-ip",
    label: "Crestron DM-NVX-351",
    manufacturer: "Crestron",
    modelNumber: "DM-NVX-351",
    referenceUrl: "https://www.crestron.com/Products/Catalog/AV-Over-IP/DM-NVX-AV-Over-IP/Video-Endpoint/DM-NVX-351",
    searchTerms: ["crestron", "nvx", "av-over-ip", "networked av", "encoder", "decoder"],
    powerDrawW: 30, // typical
    heightMm: 39,
    widthMm: 236,
    depthMm: 219,
    weightKg: 0.9,
    ports: [
      port("HDMI In 1", "hdmi", "input"),
      port("HDMI In 2", "hdmi", "input"),
      port("HDMI Out", "hdmi", "output"),
      port("Ethernet 1", "ethernet", "bidirectional"),
      port("Ethernet 2", "ethernet", "bidirectional"),
      port("Analog Audio", "analog-audio", "bidirectional"),
      port("USB Host", "usb", "bidirectional"),
      port("USB Device", "usb", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
    slots: [
      { id: "nvx351-sfp-1", label: "SFP", slotFamily: "sfp", defaultCardId: "sfp-10g-sr" },
    ],
  },
  {
    id: "c0a80101-0073-4000-8000-000000000115",
    deviceType: "ndi-encoder",
    label: "Magewell HDMI→NDI",
    manufacturer: "Magewell",
    modelNumber: "Pro Convert HDMI Plus",
    referenceUrl: "https://www.magewell.com/products/pro-convert-hdmi-plus",
    searchTerms: ["magewell", "pro convert", "ndi", "encoder", "hdmi"],
    powerDrawW: 13,
    heightMm: 23,
    widthMm: 67,
    depthMm: 118,
    weightKg: 0.5,
    ports: [
      port("HDMI In", "hdmi", "input"),
      port("HDMI Loop", "hdmi", "output"),
      port("Ethernet", "ethernet", "bidirectional"),
    ],
  },
  {
    id: "c0a80101-0074-4000-8000-000000000116",
    deviceType: "ndi-encoder",
    label: "Magewell HDMI 4K→NDI",
    manufacturer: "Magewell",
    modelNumber: "Pro Convert HDMI 4K Plus",
    referenceUrl: "https://www.magewell.com/products/pro-convert-hdmi-4k-plus",
    searchTerms: ["magewell", "pro convert", "ndi", "encoder", "4k"],
    powerDrawW: 13,
    heightMm: 23,
    widthMm: 67,
    depthMm: 118,
    weightKg: 0.5,
    ports: [
      port("HDMI 2.0 In", "hdmi", "input"),
      port("HDMI Loop", "hdmi", "output"),
      port("Ethernet", "ethernet", "bidirectional"),
    ],
  },
  {
    id: "c0a80101-0075-4000-8000-000000000117",
    deviceType: "ndi-decoder",
    label: "Magewell NDI→HDMI",
    manufacturer: "Magewell",
    modelNumber: "Pro Convert NDI to HDMI",
    referenceUrl: "https://www.magewell.com/products/pro-convert-for-ndi-to-hdmi",
    searchTerms: ["magewell", "pro convert", "ndi", "decoder"],
    powerDrawW: 13,
    heightMm: 23,
    widthMm: 60,
    depthMm: 101,
    weightKg: 0.4,
    ports: [
      port("Ethernet", "ethernet", "bidirectional"),
      port("HDMI Out", "hdmi", "output"),
    ],
  },
  // ── Streaming & Wireless ─────────────────────────────────────────
  {
    id: "c0a80101-0076-4000-8000-000000000118",
    deviceType: "streaming-encoder",
    label: "BMD Streaming Encoder HD",
    manufacturer: "Blackmagic Design",
    modelNumber: "Web Presenter HD",
    referenceUrl: "https://www.blackmagicdesign.com/products/blackmagicwebpresenter",
    searchTerms: ["blackmagic", "web presenter", "streaming", "webcam"],
    powerDrawW: 18,
    heightMm: 44,
    widthMm: 140,
    depthMm: 176,
    weightKg: 0.8,
    ports: [
      port("SDI In", "sdi", "input"),
      port("HDMI In", "hdmi", "input"),
      port("USB-C Out", "usb", "output", "usb-c"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0077-4000-8000-000000000119",
    deviceType: "streaming-encoder",
    label: "BMD Streaming Encoder 4K",
    manufacturer: "Blackmagic Design",
    modelNumber: "Web Presenter 4K",
    referenceUrl: "https://www.blackmagicdesign.com/products/blackmagicwebpresenter",
    searchTerms: ["blackmagic", "web presenter", "4k", "streaming"],
    powerDrawW: 18,
    heightMm: 44,
    widthMm: 140,
    depthMm: 176,
    weightKg: 0.8,
    ports: [
      port("12G-SDI In", "sdi", "input"),
      port("HDMI In", "hdmi", "input"),
      port("USB-C Out", "usb", "output", "usb-c"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    
      port("SDI Loop", "sdi", "output"),
    ],
  },
  {
    id: "c0a80101-0078-4000-8000-000000000120",
    deviceType: "streaming-encoder",
    label: "Teradek Cube 755",
    manufacturer: "Teradek",
    modelNumber: "Cube 755",
    referenceUrl: "https://teradek.com/products/cube-755",
    searchTerms: ["teradek", "cube", "encoder", "hevc", "h265"],
    powerDrawW: 12, // typical
    heightMm: 28,
    widthMm: 121,
    depthMm: 76,
    weightKg: 0.3,
    ports: [
      port("SDI In", "sdi", "input"),
      port("HDMI In", "hdmi", "input"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0079-4000-8000-000000000121",
    deviceType: "ndi-decoder",
    label: "Teradek Cube 775",
    manufacturer: "Teradek",
    modelNumber: "Cube 775",
    referenceUrl: "https://teradek.com/products/cube-775",
    searchTerms: ["teradek", "cube", "decoder", "hevc"],
    powerDrawW: 12, // typical
    heightMm: 28,
    widthMm: 121,
    depthMm: 76,
    weightKg: 0.3,
    ports: [
      port("Ethernet", "ethernet", "bidirectional"),
      port("SDI Out", "sdi", "output"),
      port("HDMI Out", "hdmi", "output"),
      port("AC Power", "power", "input"),
    ],
  },
  // Extron NAV AV-over-IP
  {
    id: "c0a80101-00f3-4000-8000-000000000319",
    deviceType: "av-over-ip",
    label: "Extron NAV E 101",
    manufacturer: "Extron",
    modelNumber: "NAV E 101",
    referenceUrl: "https://www.extron.com/product/nave101",
    searchTerms: ["extron", "nav", "encoder", "av over ip", "streaming", "pure3"],
    powerDrawW: 12, // typical
    heightMm: 25,
    widthMm: 222,
    depthMm: 152,
    weightKg: 0.7,
    ports: [
      port("HDMI In", "hdmi", "input"),
      port("HDMI Loop", "hdmi", "output"),
      port("Network", "ethernet", "bidirectional"),
      port("Audio In L", "analog-audio", "input", "phoenix"),
      port("Audio In R", "analog-audio", "input", "phoenix"),
      port("RS-232", "serial", "bidirectional", "phoenix"),
      port("DC Power", "power", "input", "barrel"),
    ],
  },
  {
    id: "c0a80101-00f4-4000-8000-000000000320",
    deviceType: "av-over-ip",
    label: "Extron NAV SD 101",
    manufacturer: "Extron",
    modelNumber: "NAV SD 101",
    referenceUrl: "https://www.extron.com/product/navsd101",
    searchTerms: ["extron", "nav", "decoder", "av over ip", "scaling", "pure3"],
    powerDrawW: 12, // typical
    heightMm: 25,
    widthMm: 222,
    depthMm: 152,
    weightKg: 0.7,
    ports: [
      port("HDMI Out", "hdmi", "output"),
      port("Network", "ethernet", "bidirectional"),
      port("Audio Out L", "analog-audio", "output", "phoenix"),
      port("Audio Out R", "analog-audio", "output", "phoenix"),
      port("RS-232", "serial", "bidirectional", "phoenix"),
      port("DC Power", "power", "input", "barrel"),
    ],
  },
  {
    id: "c0a80101-00fb-4000-8000-000000000327",
    deviceType: "streaming-encoder",
    category: "streaming",
    label: "BMD Streaming Decoder 4K",
    manufacturer: "Blackmagic Design",
    modelNumber: "Streaming Decoder 4K",
    referenceUrl: "https://www.blackmagicdesign.com/products/blackmagicwebpresenter",
    searchTerms: ["blackmagic", "streaming", "decoder", "srt", "rtmp"],
    powerDrawW: 18, // typical
    heightMm: 44,
    widthMm: 140,
    depthMm: 176,
    weightKg: 0.8,
    ports: [
      port("12G-SDI Out", "sdi", "output"),
      port("HDMI Out", "hdmi", "output"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("USB-C", "usb", "bidirectional", "usb-c"),
      port("AC Power", "power", "input"),
    ],
  },
  // Video new devices
  {
    id: "c0a80101-00ff-4000-8000-000000000331",
    deviceType: "ndi-encoder",
    category: "ndi",
    label: "BirdDog Mini HDMI",
    manufacturer: "BirdDog",
    modelNumber: "Mini HDMI",
    referenceUrl: "https://birddog.tv/mini-overview/",
    searchTerms: ["birddog", "mini", "ndi", "encoder", "hdmi", "poe"],
    powerDrawW: 7, // PoE powered
    heightMm: 22,
    widthMm: 98,
    depthMm: 110,
    weightKg: 0.2,
    ports: [
      port("HDMI In", "hdmi", "input"),
      port("Ethernet", "ethernet", "bidirectional"),
    ],
  },
  {
    id: "c0a80101-0100-4000-8000-000000000332",
    deviceType: "ndi-encoder",
    category: "ndi",
    label: "Kiloview E2",
    manufacturer: "Kiloview",
    modelNumber: "E2",
    referenceUrl: "https://www.kiloview.com/en/ndi/ndi-wired/",
    searchTerms: ["kiloview", "e2", "ndi", "encoder", "hdmi"],
    powerDrawW: 12, // typical
    heightMm: 28,
    widthMm: 125,
    depthMm: 89,
    weightKg: 0.4,
    ports: [
      port("HDMI In", "hdmi", "input"),
      port("Ethernet", "ethernet", "bidirectional"),
    ],
  },
  {
    id: "c0a80101-0105-4000-8000-000000000337",
    deviceType: "ndi-encoder",
    category: "ndi",
    label: "Magewell USB Capture HDMI Plus",
    manufacturer: "Magewell",
    modelNumber: "USB Capture HDMI Plus",
    referenceUrl: "https://www.magewell.com/products/usb-capture-hdmi-plus",
    searchTerms: ["magewell", "usb capture", "hdmi", "capture card"],
    powerDrawW: 0, // USB bus-powered
    heightMm: 17,
    widthMm: 57,
    depthMm: 98,
    weightKg: 0.2,
    ports: [
      port("HDMI In", "hdmi", "input"),
      port("HDMI Loop", "hdmi", "output"),
      port("3.5mm Audio In", "analog-audio", "input", "trs-eighth"),
      port("3.5mm Audio Out", "analog-audio", "output", "trs-eighth"),
      port("USB-B 3.0", "usb", "output", "usb-b"),
    ],
  },
  {
    id: "c0a80101-0106-4000-8000-000000000338",
    deviceType: "ndi-encoder",
    category: "ndi",
    label: "Magewell SDI→NDI",
    manufacturer: "Magewell",
    modelNumber: "Pro Convert SDI Plus",
    referenceUrl: "https://www.magewell.com/products/pro-convert-sdi-plus",
    searchTerms: ["magewell", "pro convert", "ndi", "encoder", "sdi"],
    powerDrawW: 13,
    heightMm: 23,
    widthMm: 67,
    depthMm: 118,
    weightKg: 0.4,
    ports: [
      port("SDI In", "sdi", "input"),
      port("SDI Loop", "sdi", "output"),
      port("Ethernet", "ethernet", "bidirectional"),
    ],
  },
  // ── NETGEAR AV Line managed switches (M4250 / M4350) ────────────
  {
    id: "c0a80101-033c-4000-8000-000000000782",
    deviceType: "network-switch",
    label: "Netgear M4250-9G1F-PoE+",
    manufacturer: "Netgear",
    modelNumber: "M4250-9G1F-PoE+",
    referenceUrl: "https://www.downloads.netgear.com/files/GDC/M4250/M4250_Datasheet.pdf",
    searchTerms: ["netgear", "av line", "m4250", "m4250-9g1f-poe+", "gsm4210pd", "switch", "managed", "igmp", "desktop", "fanless"],
    powerDrawW: 132.25, // maximum, full traffic and max PoE load
    poeBudgetW: 110, // maximum PoE budget
    thermalBtuh: 451.5,
    voltage: "100-240V",
    heightMm: 40,
    widthMm: 210,
    depthMm: 140,
    weightKg: 0.97,
    rackForm: "shelf-only",
    ports: [
      ...ports("PoE+ Port", "ethernet", "bidirectional", 8),
      ...ports("Port", "ethernet", "bidirectional", 1),
      port("SFP 1 (1G)", "ethernet", "bidirectional", "sfp"),
      port("OOB Mgmt", "ethernet", "bidirectional"),
      port("Console (USB-C)", "usb", "bidirectional", "usb-c"),
      port("DC Power (Adapter)", "power", "input", "barrel"),
    ],
  },
  {
    id: "c0a80101-033d-4000-8000-000000000783",
    deviceType: "network-switch",
    label: "Netgear M4250-8G2XF-PoE+",
    manufacturer: "Netgear",
    modelNumber: "M4250-8G2XF-PoE+",
    referenceUrl: "https://www.downloads.netgear.com/files/GDC/M4250/M4250_Datasheet.pdf",
    searchTerms: ["netgear", "av line", "m4250", "m4250-8g2xf-poe+", "gsm4210px", "switch", "managed", "igmp", "desktop"],
    powerDrawW: 257.9, // maximum, full traffic and max PoE load
    poeBudgetW: 220, // maximum PoE budget
    thermalBtuh: 880.47,
    voltage: "100-240V",
    heightMm: 40,
    widthMm: 210,
    depthMm: 140,
    weightKg: 0.97,
    rackForm: "shelf-only",
    ports: [
      ...ports("PoE+ Port", "ethernet", "bidirectional", 8),
      ...Array.from({ length: 2 }, (_, i) => port(`SFP+ ${i + 1} (10G)`, "ethernet", "bidirectional", "sfp")),
      port("OOB Mgmt", "ethernet", "bidirectional"),
      port("Console (USB-C)", "usb", "bidirectional", "usb-c"),
      port("DC Power (Adapter)", "power", "input", "barrel"),
    ],
  },
  {
    id: "c0a80101-033e-4000-8000-000000000784",
    deviceType: "network-switch",
    label: "Netgear M4250-10G2F-PoE+",
    manufacturer: "Netgear",
    modelNumber: "M4250-10G2F-PoE+",
    referenceUrl: "https://www.downloads.netgear.com/files/GDC/M4250/M4250_Datasheet.pdf",
    searchTerms: ["netgear", "av line", "m4250", "m4250-10g2f-poe+", "gsm4212p", "switch", "managed", "igmp"],
    powerDrawW: 163.9, // maximum, full traffic and max PoE load
    poeBudgetW: 125, // maximum PoE budget
    thermalBtuh: 559.55,
    voltage: "100-240V",
    heightMm: 43,
    widthMm: 440,
    depthMm: 200,
    weightKg: 2.85,
    rackForm: "full",
    ports: [
      ...ports("PoE+ Port", "ethernet", "bidirectional", 8),
      ...ports("Port", "ethernet", "bidirectional", 2),
      ...Array.from({ length: 2 }, (_, i) => port(`SFP ${i + 1} (1G)`, "ethernet", "bidirectional", "sfp")),
      port("OOB Mgmt", "ethernet", "bidirectional"),
      port("Console (RJ45)", "serial", "bidirectional", "rj45"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-033f-4000-8000-000000000785",
    deviceType: "network-switch",
    label: "Netgear M4250-10G2XF-PoE+",
    manufacturer: "Netgear",
    modelNumber: "M4250-10G2XF-PoE+",
    referenceUrl: "https://www.downloads.netgear.com/files/GDC/M4250/M4250_Datasheet.pdf",
    searchTerms: ["netgear", "av line", "m4250", "m4250-10g2xf-poe+", "gsm4212px", "switch", "managed", "igmp"],
    powerDrawW: 306.4, // maximum, full traffic and max PoE load
    poeBudgetW: 240, // maximum PoE budget
    thermalBtuh: 1046.05,
    voltage: "100-240V",
    heightMm: 43,
    widthMm: 440,
    depthMm: 200,
    weightKg: 2.9,
    rackForm: "full",
    ports: [
      ...ports("PoE+ Port", "ethernet", "bidirectional", 8),
      ...ports("Port", "ethernet", "bidirectional", 2),
      ...Array.from({ length: 2 }, (_, i) => port(`SFP+ ${i + 1} (10G)`, "ethernet", "bidirectional", "sfp")),
      port("OOB Mgmt", "ethernet", "bidirectional"),
      port("Console (RJ45)", "serial", "bidirectional", "rj45"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0340-4000-8000-000000000786",
    deviceType: "network-switch",
    label: "Netgear M4250-10G2XF-PoE++",
    manufacturer: "Netgear",
    modelNumber: "M4250-10G2XF-PoE++",
    referenceUrl: "https://www.downloads.netgear.com/files/GDC/M4250/M4250_Datasheet.pdf",
    searchTerms: ["netgear", "av line", "m4250", "m4250-10g2xf-poe++", "gsm4212ux", "switch", "managed", "igmp", "poe++", "802.3bt", "90w"],
    powerDrawW: 837.7, // maximum, full traffic and max PoE load
    poeBudgetW: 720, // Ultra90 802.3bt
    thermalBtuh: 2859.91,
    voltage: "100-240V",
    heightMm: 43,
    widthMm: 440,
    depthMm: 257,
    weightKg: 3.83,
    rackForm: "full",
    ports: [
      ...ports("PoE++ Port", "ethernet", "bidirectional", 8),
      ...ports("Port", "ethernet", "bidirectional", 2),
      ...Array.from({ length: 2 }, (_, i) => port(`SFP+ ${i + 1} (10G)`, "ethernet", "bidirectional", "sfp")),
      port("OOB Mgmt", "ethernet", "bidirectional"),
      port("Console (RJ45)", "serial", "bidirectional", "rj45"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0341-4000-8000-000000000787",
    deviceType: "network-switch",
    label: "Netgear M4250-12M2XF",
    manufacturer: "Netgear",
    modelNumber: "M4250-12M2XF",
    referenceUrl: "https://www.downloads.netgear.com/files/GDC/M4250/M4250_Datasheet.pdf",
    searchTerms: ["netgear", "av line", "m4250", "m4250-12m2xf", "msm4214x", "switch", "managed", "igmp", "2.5g", "multi-gig"],
    powerDrawW: 37.9, // maximum, full traffic and max PoE load
    thermalBtuh: 129.39,
    voltage: "100-240V",
    heightMm: 43,
    widthMm: 440,
    depthMm: 100,
    weightKg: 1.74,
    rackForm: "full",
    ports: [
      ...Array.from({ length: 12 }, (_, i) => port(`Port ${i + 1} (2.5G)`, "ethernet", "bidirectional")),
      ...Array.from({ length: 2 }, (_, i) => port(`SFP+ ${i + 1} (10G)`, "ethernet", "bidirectional", "sfp")),
      port("OOB Mgmt", "ethernet", "bidirectional"),
      port("Console (RJ45)", "serial", "bidirectional", "rj45"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0342-4000-8000-000000000788",
    deviceType: "network-switch",
    label: "Netgear M4250-16XF",
    manufacturer: "Netgear",
    modelNumber: "M4250-16XF",
    referenceUrl: "https://www.downloads.netgear.com/files/GDC/M4250/M4250_Datasheet.pdf",
    searchTerms: ["netgear", "av line", "m4250", "m4250-16xf", "xsm4216f", "switch", "managed", "igmp", "fiber", "aggregation"],
    powerDrawW: 47.84, // maximum, full traffic and max PoE load
    thermalBtuh: 163.33,
    voltage: "100-240V",
    heightMm: 43,
    widthMm: 440,
    depthMm: 200,
    weightKg: 2.8,
    rackForm: "full",
    ports: [
      ...Array.from({ length: 16 }, (_, i) => port(`SFP+ ${i + 1} (10G)`, "ethernet", "bidirectional", "sfp")),
      port("OOB Mgmt", "ethernet", "bidirectional"),
      port("Console (RJ45)", "serial", "bidirectional", "rj45"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0343-4000-8000-000000000789",
    deviceType: "network-switch",
    label: "Netgear M4250-26G4F-PoE+",
    manufacturer: "Netgear",
    modelNumber: "M4250-26G4F-PoE+",
    referenceUrl: "https://www.downloads.netgear.com/files/GDC/M4250/M4250_Datasheet.pdf",
    searchTerms: ["netgear", "av line", "m4250", "m4250-26g4f-poe+", "gsm4230p", "switch", "managed", "igmp"],
    powerDrawW: 401, // maximum, full traffic and max PoE load
    poeBudgetW: 300, // maximum PoE budget
    thermalBtuh: 1369.01,
    voltage: "100-240V",
    heightMm: 43,
    widthMm: 440,
    depthMm: 257,
    weightKg: 4.3,
    rackForm: "full",
    ports: [
      ...ports("PoE+ Port", "ethernet", "bidirectional", 24),
      ...ports("Port", "ethernet", "bidirectional", 2),
      ...Array.from({ length: 4 }, (_, i) => port(`SFP ${i + 1} (1G)`, "ethernet", "bidirectional", "sfp")),
      port("OOB Mgmt", "ethernet", "bidirectional"),
      port("Console (RJ45)", "serial", "bidirectional", "rj45"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0344-4000-8000-000000000790",
    deviceType: "network-switch",
    label: "Netgear M4250-26G4F-PoE++",
    manufacturer: "Netgear",
    modelNumber: "M4250-26G4F-PoE++",
    referenceUrl: "https://www.downloads.netgear.com/files/GDC/M4250/M4250_Datasheet.pdf",
    searchTerms: ["netgear", "av line", "m4250", "m4250-26g4f-poe++", "gsm4230up", "switch", "managed", "igmp", "poe++", "802.3bt", "90w"],
    powerDrawW: 1734, // maximum, full traffic and max PoE load
    poeBudgetW: 1440, // 720W with one PSU; Ultra90 802.3bt
    thermalBtuh: 5919.88,
    voltage: "100-240V",
    heightMm: 43,
    widthMm: 440,
    depthMm: 400,
    weightKg: 6.75,
    rackForm: "full",
    ports: [
      ...ports("PoE++ Port", "ethernet", "bidirectional", 24),
      ...ports("Port", "ethernet", "bidirectional", 2),
      ...Array.from({ length: 4 }, (_, i) => port(`SFP ${i + 1} (1G)`, "ethernet", "bidirectional", "sfp")),
      port("OOB Mgmt", "ethernet", "bidirectional"),
      port("Console (RJ45)", "serial", "bidirectional", "rj45"),
      port("AC Power 1", "power", "input"),
      port("AC Power 2", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0345-4000-8000-000000000791",
    deviceType: "network-switch",
    label: "Netgear M4250-26G4XF-PoE+",
    manufacturer: "Netgear",
    modelNumber: "M4250-26G4XF-PoE+",
    referenceUrl: "https://www.downloads.netgear.com/files/GDC/M4250/M4250_Datasheet.pdf",
    searchTerms: ["netgear", "av line", "m4250", "m4250-26g4xf-poe+", "gsm4230px", "switch", "managed", "igmp"],
    powerDrawW: 614, // maximum, full traffic and max PoE load
    poeBudgetW: 480, // maximum PoE budget
    thermalBtuh: 2096.2,
    voltage: "100-240V",
    heightMm: 43,
    widthMm: 440,
    depthMm: 400,
    weightKg: 5.45,
    rackForm: "full",
    ports: [
      ...ports("PoE+ Port", "ethernet", "bidirectional", 24),
      ...ports("Port", "ethernet", "bidirectional", 2),
      ...Array.from({ length: 4 }, (_, i) => port(`SFP+ ${i + 1} (10G)`, "ethernet", "bidirectional", "sfp")),
      port("OOB Mgmt", "ethernet", "bidirectional"),
      port("Console (RJ45)", "serial", "bidirectional", "rj45"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0346-4000-8000-000000000792",
    deviceType: "network-switch",
    label: "Netgear M4250-40G8F-PoE+",
    manufacturer: "Netgear",
    modelNumber: "M4250-40G8F-PoE+",
    referenceUrl: "https://www.downloads.netgear.com/files/GDC/M4250/M4250_Datasheet.pdf",
    searchTerms: ["netgear", "av line", "m4250", "m4250-40g8f-poe+", "gsm4248p", "switch", "managed", "igmp"],
    powerDrawW: 624.8, // maximum, full traffic and max PoE load
    poeBudgetW: 480, // maximum PoE budget
    thermalBtuh: 2133.07,
    voltage: "100-240V",
    heightMm: 43,
    widthMm: 440,
    depthMm: 400,
    weightKg: 5.85,
    rackForm: "full",
    ports: [
      ...ports("PoE+ Port", "ethernet", "bidirectional", 40),
      ...Array.from({ length: 8 }, (_, i) => port(`SFP ${i + 1} (1G)`, "ethernet", "bidirectional", "sfp")),
      port("OOB Mgmt", "ethernet", "bidirectional"),
      port("Console (RJ45)", "serial", "bidirectional", "rj45"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0347-4000-8000-000000000793",
    deviceType: "network-switch",
    label: "Netgear M4250-40G8XF-PoE+",
    manufacturer: "Netgear",
    modelNumber: "M4250-40G8XF-PoE+",
    referenceUrl: "https://www.downloads.netgear.com/files/GDC/M4250/M4250_Datasheet.pdf",
    searchTerms: ["netgear", "av line", "m4250", "m4250-40g8xf-poe+", "gsm4248px", "switch", "managed", "igmp"],
    powerDrawW: 1197, // maximum, full traffic and max PoE load
    poeBudgetW: 960, // maximum PoE budget
    thermalBtuh: 4086.56,
    voltage: "100-240V",
    heightMm: 43,
    widthMm: 440,
    depthMm: 400,
    weightKg: 6.31,
    rackForm: "full",
    ports: [
      ...ports("PoE+ Port", "ethernet", "bidirectional", 40),
      ...Array.from({ length: 8 }, (_, i) => port(`SFP+ ${i + 1} (10G)`, "ethernet", "bidirectional", "sfp")),
      port("OOB Mgmt", "ethernet", "bidirectional"),
      port("Console (RJ45)", "serial", "bidirectional", "rj45"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0348-4000-8000-000000000794",
    deviceType: "network-switch",
    label: "Netgear M4250-40G8XF-PoE++",
    manufacturer: "Netgear",
    modelNumber: "M4250-40G8XF-PoE++",
    referenceUrl: "https://www.downloads.netgear.com/files/GDC/M4250/M4250_Datasheet.pdf",
    searchTerms: ["netgear", "av line", "m4250", "m4250-40g8xf-poe++", "gsm4248ux", "switch", "managed", "igmp", "poe++", "802.3bt", "90w"],
    powerDrawW: 3523, // maximum, full traffic and max PoE load
    poeBudgetW: 2880, // 720W/1650W with one/two PSUs; Ultra90 802.3bt; 2U
    thermalBtuh: 12027.52,
    voltage: "100-240V",
    heightMm: 86,
    widthMm: 440,
    depthMm: 350,
    weightKg: 10.28,
    rackForm: "full",
    ports: [
      ...ports("PoE++ Port", "ethernet", "bidirectional", 40),
      ...Array.from({ length: 8 }, (_, i) => port(`SFP+ ${i + 1} (10G)`, "ethernet", "bidirectional", "sfp")),
      port("OOB Mgmt", "ethernet", "bidirectional"),
      port("Console (RJ45)", "serial", "bidirectional", "rj45"),
      port("AC Power 1", "power", "input"),
      port("AC Power 2", "power", "input"),
      port("AC Power 3", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0349-4000-8000-000000000795",
    deviceType: "network-switch",
    label: "Netgear M4350-24G4XF",
    manufacturer: "Netgear",
    modelNumber: "M4350-24G4XF",
    referenceUrl: "https://www.downloads.netgear.com/files/GDC/M4350/M4350_Datasheet.pdf",
    searchTerms: ["netgear", "av line", "m4350", "m4350-24g4xf", "gsm4328", "switch", "managed", "igmp", "stacking"],
    powerDrawW: 871.2, // maximum, full traffic and max PoE load
    poeBudgetW: 720, // 648W base with internal PSU
    thermalBtuh: 2972.73,
    voltage: "100-240V",
    heightMm: 43,
    widthMm: 440,
    depthMm: 400,
    weightKg: 6.41,
    rackForm: "full",
    ports: [
      ...ports("PoE+ Port", "ethernet", "bidirectional", 24),
      ...Array.from({ length: 4 }, (_, i) => port(`SFP+ ${i + 1} (10G)`, "ethernet", "bidirectional", "sfp")),
      port("OOB Mgmt", "ethernet", "bidirectional"),
      port("Console (USB-C)", "usb", "bidirectional", "usb-c"),
      port("AC Power 1", "power", "input"),
      port("AC Power 2 (modular)", "power", "input"),
    ],
  },
  {
    id: "c0a80101-034a-4000-8000-000000000796",
    deviceType: "network-switch",
    label: "Netgear M4350-48G4XF",
    manufacturer: "Netgear",
    modelNumber: "M4350-48G4XF",
    referenceUrl: "https://www.downloads.netgear.com/files/GDC/M4350/M4350_Datasheet.pdf",
    searchTerms: ["netgear", "av line", "m4350", "m4350-48g4xf", "gsm4352", "switch", "managed", "igmp", "stacking"],
    powerDrawW: 1618.3, // maximum, full traffic and max PoE load
    poeBudgetW: 1440, // 236W base with internal PSU
    thermalBtuh: 5521.94,
    voltage: "100-240V",
    heightMm: 43,
    widthMm: 440,
    depthMm: 400,
    weightKg: 7.19,
    rackForm: "full",
    ports: [
      ...ports("PoE+ Port", "ethernet", "bidirectional", 48),
      ...Array.from({ length: 4 }, (_, i) => port(`SFP+ ${i + 1} (10G)`, "ethernet", "bidirectional", "sfp")),
      port("OOB Mgmt", "ethernet", "bidirectional"),
      port("Console (USB-C)", "usb", "bidirectional", "usb-c"),
      port("AC Power 1", "power", "input"),
      port("AC Power 2 (modular)", "power", "input"),
      port("AC Power 3 (modular)", "power", "input"),
    ],
  },
  {
    id: "c0a80101-034b-4000-8000-000000000797",
    deviceType: "network-switch",
    label: "Netgear M4350-44M4X4V",
    manufacturer: "Netgear",
    modelNumber: "M4350-44M4X4V",
    referenceUrl: "https://www.downloads.netgear.com/files/GDC/M4350/M4350_Datasheet.pdf",
    searchTerms: ["netgear", "av line", "m4350", "m4350-44m4x4v", "msm4352", "switch", "managed", "igmp", "poe++", "2.5g", "multi-gig", "25g"],
    powerDrawW: 3857.5, // maximum, full traffic and max PoE load
    poeBudgetW: 3314, // 194W base with internal PSU; Ultra90 802.3bt
    thermalBtuh: 13162.27,
    voltage: "100-240V",
    heightMm: 43,
    widthMm: 440,
    depthMm: 400,
    weightKg: 7.34,
    rackForm: "full",
    ports: [
      ...Array.from({ length: 44 }, (_, i) => port(`PoE++ Port ${i + 1} (2.5G)`, "ethernet", "bidirectional")),
      ...Array.from({ length: 4 }, (_, i) => port(`PoE++ Port ${i + 1} (10G)`, "ethernet", "bidirectional")),
      ...Array.from({ length: 4 }, (_, i) => port(`SFP28 ${i + 1} (25G)`, "ethernet", "bidirectional", "sfp")),
      port("OOB Mgmt", "ethernet", "bidirectional"),
      port("Console (USB-C)", "usb", "bidirectional", "usb-c"),
      port("AC Power 1", "power", "input"),
      port("AC Power 2 (modular)", "power", "input"),
      port("AC Power 3 (modular)", "power", "input"),
    ],
  },
  {
    id: "c0a80101-034c-4000-8000-000000000798",
    deviceType: "network-switch",
    label: "Netgear M4350-8X8F",
    manufacturer: "Netgear",
    modelNumber: "M4350-8X8F",
    referenceUrl: "https://www.downloads.netgear.com/files/GDC/M4350/M4350_Datasheet.pdf",
    searchTerms: ["netgear", "av line", "m4350", "m4350-8x8f", "xsm4316", "switch", "managed", "igmp", "multi-gig", "half-width"],
    powerDrawW: 81.1, // maximum, full traffic and max PoE load
    thermalBtuh: 276.72,
    voltage: "100-240V",
    heightMm: 43,
    widthMm: 220,
    depthMm: 400,
    weightKg: 4.05,
    rackForm: "half",
    ports: [
      ...Array.from({ length: 8 }, (_, i) => port(`Port ${i + 1} (10G)`, "ethernet", "bidirectional")),
      ...Array.from({ length: 8 }, (_, i) => port(`SFP+ ${i + 1} (10G)`, "ethernet", "bidirectional", "sfp")),
      port("OOB Mgmt", "ethernet", "bidirectional"),
      port("Console (USB-C)", "usb", "bidirectional", "usb-c"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-034d-4000-8000-000000000799",
    deviceType: "network-switch",
    label: "Netgear M4350-12X12F",
    manufacturer: "Netgear",
    modelNumber: "M4350-12X12F",
    referenceUrl: "https://www.downloads.netgear.com/files/GDC/M4350/M4350_Datasheet.pdf",
    searchTerms: ["netgear", "av line", "m4350", "m4350-12x12f", "xsm4324", "switch", "managed", "igmp", "multi-gig", "half-width"],
    powerDrawW: 95.8, // maximum, full traffic and max PoE load
    thermalBtuh: 326.88,
    voltage: "100-240V",
    heightMm: 43,
    widthMm: 220,
    depthMm: 400,
    weightKg: 4.3,
    rackForm: "half",
    ports: [
      ...Array.from({ length: 12 }, (_, i) => port(`Port ${i + 1} (10G)`, "ethernet", "bidirectional")),
      ...Array.from({ length: 12 }, (_, i) => port(`SFP+ ${i + 1} (10G)`, "ethernet", "bidirectional", "sfp")),
      port("OOB Mgmt", "ethernet", "bidirectional"),
      port("Console (USB-C)", "usb", "bidirectional", "usb-c"),
      port("AC Power", "power", "input"),
    ],
  },
  {
    id: "c0a80101-034e-4000-8000-000000000800",
    deviceType: "network-switch",
    label: "Netgear M4350-24X4V",
    manufacturer: "Netgear",
    modelNumber: "M4350-24X4V",
    referenceUrl: "https://www.downloads.netgear.com/files/GDC/M4350/M4350_Datasheet.pdf",
    searchTerms: ["netgear", "av line", "m4350", "m4350-24x4v", "xsm4328cv", "switch", "managed", "igmp", "multi-gig", "25g"],
    powerDrawW: 907.8, // maximum, full traffic and max PoE load
    poeBudgetW: 720, // 576W base with internal PSU
    thermalBtuh: 3097.46,
    voltage: "100-240V",
    heightMm: 43,
    widthMm: 440,
    depthMm: 400,
    weightKg: 6.58,
    rackForm: "full",
    ports: [
      ...Array.from({ length: 24 }, (_, i) => port(`PoE+ Port ${i + 1} (10G)`, "ethernet", "bidirectional")),
      ...Array.from({ length: 4 }, (_, i) => port(`SFP28 ${i + 1} (25G)`, "ethernet", "bidirectional", "sfp")),
      port("OOB Mgmt", "ethernet", "bidirectional"),
      port("Console (USB-C)", "usb", "bidirectional", "usb-c"),
      port("AC Power 1", "power", "input"),
      port("AC Power 2 (modular)", "power", "input"),
    ],
  },
  {
    id: "c0a80101-034f-4000-8000-000000000801",
    deviceType: "network-switch",
    label: "Netgear M4350-24F4V",
    manufacturer: "Netgear",
    modelNumber: "M4350-24F4V",
    referenceUrl: "https://www.downloads.netgear.com/files/GDC/M4350/M4350_Datasheet.pdf",
    searchTerms: ["netgear", "av line", "m4350", "m4350-24f4v", "xsm4328fv", "switch", "managed", "igmp", "fiber", "25g"],
    powerDrawW: 119.3, // maximum, full traffic and max PoE load
    thermalBtuh: 407.07,
    voltage: "100-240V",
    heightMm: 43,
    widthMm: 440,
    depthMm: 400,
    weightKg: 6.25,
    rackForm: "full",
    ports: [
      ...Array.from({ length: 24 }, (_, i) => port(`SFP+ ${i + 1} (10G)`, "ethernet", "bidirectional", "sfp")),
      ...Array.from({ length: 4 }, (_, i) => port(`SFP28 ${i + 1} (25G)`, "ethernet", "bidirectional", "sfp")),
      port("OOB Mgmt", "ethernet", "bidirectional"),
      port("Console (USB-C)", "usb", "bidirectional", "usb-c"),
      port("AC Power 1", "power", "input"),
      port("AC Power 2 (modular)", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0350-4000-8000-000000000802",
    deviceType: "network-switch",
    label: "Netgear M4350-36X4V",
    manufacturer: "Netgear",
    modelNumber: "M4350-36X4V",
    referenceUrl: "https://www.downloads.netgear.com/files/GDC/M4350/M4350_Datasheet.pdf",
    searchTerms: ["netgear", "av line", "m4350", "m4350-36x4v", "xsm4340cv", "switch", "managed", "igmp", "poe++", "multi-gig", "25g"],
    powerDrawW: 2071.4, // maximum, full traffic and max PoE load
    poeBudgetW: 1760, // 280W base with internal PSU; Ultra90 802.3bt
    thermalBtuh: 7068.01,
    voltage: "100-240V",
    heightMm: 43,
    widthMm: 440,
    depthMm: 400,
    weightKg: 7.33,
    rackForm: "full",
    ports: [
      ...Array.from({ length: 36 }, (_, i) => port(`PoE++ Port ${i + 1} (10G)`, "ethernet", "bidirectional")),
      ...Array.from({ length: 4 }, (_, i) => port(`SFP28 ${i + 1} (25G)`, "ethernet", "bidirectional", "sfp")),
      port("OOB Mgmt", "ethernet", "bidirectional"),
      port("Console (USB-C)", "usb", "bidirectional", "usb-c"),
      port("AC Power 1", "power", "input"),
      port("AC Power 2 (modular)", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0351-4000-8000-000000000803",
    deviceType: "network-switch",
    label: "Netgear M4350-24X8F8V",
    manufacturer: "Netgear",
    modelNumber: "M4350-24X8F8V",
    referenceUrl: "https://www.downloads.netgear.com/files/GDC/M4350/M4350_Datasheet.pdf",
    searchTerms: ["netgear", "av line", "m4350", "m4350-24x8f8v", "xsm4340v", "switch", "managed", "igmp", "poe++", "multi-gig", "25g"],
    powerDrawW: 2057.3, // maximum, full traffic and max PoE load
    poeBudgetW: 1770, // 290W base with internal PSU; Ultra90 802.3bt
    thermalBtuh: 7019.79,
    voltage: "100-240V",
    heightMm: 43,
    widthMm: 440,
    depthMm: 400,
    weightKg: 7.24,
    rackForm: "full",
    ports: [
      ...Array.from({ length: 24 }, (_, i) => port(`PoE++ Port ${i + 1} (10G)`, "ethernet", "bidirectional")),
      ...Array.from({ length: 8 }, (_, i) => port(`SFP+ ${i + 1} (10G)`, "ethernet", "bidirectional", "sfp")),
      ...Array.from({ length: 8 }, (_, i) => port(`SFP28 ${i + 1} (25G)`, "ethernet", "bidirectional", "sfp")),
      port("OOB Mgmt", "ethernet", "bidirectional"),
      port("Console (USB-C)", "usb", "bidirectional", "usb-c"),
      port("AC Power 1", "power", "input"),
      port("AC Power 2 (modular)", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0352-4000-8000-000000000804",
    deviceType: "network-switch",
    label: "Netgear M4350-32F8V",
    manufacturer: "Netgear",
    modelNumber: "M4350-32F8V",
    referenceUrl: "https://www.downloads.netgear.com/files/GDC/M4350/M4350_Datasheet.pdf",
    searchTerms: ["netgear", "av line", "m4350", "m4350-32f8v", "xsm4340fv", "switch", "managed", "igmp", "fiber", "25g"],
    powerDrawW: 156.4, // maximum, full traffic and max PoE load
    thermalBtuh: 533.66,
    voltage: "100-240V",
    heightMm: 43,
    widthMm: 440,
    depthMm: 400,
    weightKg: 6.95,
    rackForm: "full",
    ports: [
      ...Array.from({ length: 32 }, (_, i) => port(`SFP+ ${i + 1} (10G)`, "ethernet", "bidirectional", "sfp")),
      ...Array.from({ length: 8 }, (_, i) => port(`SFP28 ${i + 1} (25G)`, "ethernet", "bidirectional", "sfp")),
      port("OOB Mgmt", "ethernet", "bidirectional"),
      port("Console (USB-C)", "usb", "bidirectional", "usb-c"),
      port("AC Power 1", "power", "input"),
      port("AC Power 2 (modular)", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0353-4000-8000-000000000805",
    deviceType: "network-switch",
    label: "Netgear M4350-16V4C",
    manufacturer: "Netgear",
    modelNumber: "M4350-16V4C",
    referenceUrl: "https://www.downloads.netgear.com/files/GDC/M4350/M4350_Datasheet.pdf",
    searchTerms: ["netgear", "av line", "m4350", "m4350-16v4c", "vsm4320c", "switch", "managed", "igmp", "25g", "100g", "st 2110", "spine"],
    powerDrawW: 143.4, // maximum, full traffic and max PoE load
    thermalBtuh: 489.3,
    voltage: "100-240V",
    heightMm: 43,
    widthMm: 440,
    depthMm: 400,
    weightKg: 7.15,
    rackForm: "full",
    ports: [
      ...Array.from({ length: 16 }, (_, i) => port(`SFP28 ${i + 1} (25G)`, "ethernet", "bidirectional", "sfp")),
      ...Array.from({ length: 4 }, (_, i) => port(`QSFP28 ${i + 1} (100G)`, "ethernet", "bidirectional", "sfp")),
      port("OOB Mgmt", "ethernet", "bidirectional"),
      port("Console (USB-C)", "usb", "bidirectional", "usb-c"),
      port("AC Power 1", "power", "input"),
      port("AC Power 2 (modular)", "power", "input"),
    ],
  },
  {
    id: "c0a80101-0354-4000-8000-000000000806",
    deviceType: "network-switch",
    label: "Netgear M4350-40X4C",
    manufacturer: "Netgear",
    modelNumber: "M4350-40X4C",
    referenceUrl: "https://www.downloads.netgear.com/files/GDC/M4350/M4350_Datasheet.pdf",
    searchTerms: ["netgear", "av line", "m4350", "m4350-40x4c", "xsm4344c", "switch", "managed", "igmp", "poe++", "multi-gig", "100g", "st 2110"],
    powerDrawW: 2018.3, // maximum, full traffic and max PoE load
    poeBudgetW: 1676, // 196W base with internal PSU; Ultra90 802.3bt
    thermalBtuh: 6886.89,
    voltage: "100-240V",
    heightMm: 43,
    widthMm: 440,
    depthMm: 400,
    weightKg: 7.76,
    rackForm: "full",
    ports: [
      ...Array.from({ length: 40 }, (_, i) => port(`PoE++ Port ${i + 1} (10G)`, "ethernet", "bidirectional")),
      ...Array.from({ length: 4 }, (_, i) => port(`QSFP28 ${i + 1} (100G)`, "ethernet", "bidirectional", "sfp")),
      port("OOB Mgmt", "ethernet", "bidirectional"),
      port("Console (USB-C)", "usb", "bidirectional", "usb-c"),
      port("AC Power 1", "power", "input"),
      port("AC Power 2 (modular)", "power", "input"),
    ],
  },
  // ── Evertz NUCLEUS UXP AV-over-IP gateways (client package import) ──
  {
    id: "c0a80101-035f-4000-8000-000000000817",
    deviceType: "av-over-ip",
    label: "Evertz UXP-TRM4K-2U",
    manufacturer: "Evertz",
    modelNumber: "UXP-TRM4K-2U",
    referenceUrl: "https://av.evertz.com/pdf/product/UXP-TRM4K-2.pdf",
    searchTerms: ["evertz", "uxp", "nucleus", "av over ip", "ipmx", "gateway", "trm4k", "trxm4k", "4k"],
    powerDrawW: 40,
    ports: [
      port("HDMI In 1", "hdmi", "input"),
      port("HDMI In 2", "hdmi", "input"),
      port("HDMI Out 1", "hdmi", "output"),
      port("HDMI Out 2", "hdmi", "output"),
      port("Audio In", "analog-audio", "input", "phoenix"),
      port("Audio Out", "analog-audio", "output", "phoenix"),
      port("USB (HID Host)", "usb", "bidirectional", "usb-b"),
      port("SFP+ 1 (Transport)", "ethernet", "bidirectional", "sfp"),
      port("SFP+ 2 (Transport)", "ethernet", "bidirectional", "sfp"),
      port("DC Power (12V)", "power", "input", "barrel"),
    ],
  },
  {
    id: "c0a80101-0360-4000-8000-000000000818",
    deviceType: "av-over-ip",
    label: "Evertz UXP-TRXS4K-USB2",
    manufacturer: "Evertz",
    modelNumber: "UXP-TRXS4K-USB2",
    referenceUrl: "https://av.evertz.com/pdf/product/UXP-TRXS4K-USB2.pdf",
    searchTerms: ["evertz", "uxp", "nucleus", "av over ip", "ipmx", "gateway", "trxs4k", "usb", "4k"],
    heightMm: 33,
    widthMm: 105,
    depthMm: 190,
    rackForm: "shelf-only",
    ports: [
      port("HDMI In", "hdmi", "input"),
      port("HDMI Out", "hdmi", "output"),
      port("Audio In", "analog-audio", "input", "trs-eighth"),
      port("Audio Out", "analog-audio", "output", "trs-eighth"),
      port("USB 2.0 1", "usb", "bidirectional", "usb-a"),
      port("USB 2.0 2", "usb", "bidirectional", "usb-a"),
      port("USB HID 1", "usb", "bidirectional", "usb-a"),
      port("USB HID 2", "usb", "bidirectional", "usb-a"),
      port("USB (HID Host)", "usb", "bidirectional", "usb-micro"),
      // M5 DIN serial connector; mini-din-4 is the closest library connector
      port("Serial (RS-232/422)", "serial", "bidirectional", "mini-din-4"),
      port("Control (OOB)", "ethernet", "bidirectional"),
      port("SFP+ (Transport)", "ethernet", "bidirectional", "sfp"),
      port("DC Power (12V)", "power", "input", "barrel"),
    ],
  },
  {
    id: "c0a80101-0361-4000-8000-000000000819",
    deviceType: "av-over-ip",
    label: "Evertz UXP-TRS4K-12G",
    manufacturer: "Evertz",
    modelNumber: "UXP-TRS4K-12G",
    referenceUrl: "https://av.evertz.com/pdf/product/UXP-TRS4K-12G.pdf",
    searchTerms: ["evertz", "uxp", "nucleus", "av over ip", "ipmx", "gateway", "sdi", "12g", "trs4k"],
    powerDrawW: 60, // <60 W maximum
    heightMm: 46,
    widthMm: 210,
    depthMm: 167,
    weightKg: 1.2,
    rackForm: "shelf-only",
    ports: [
      // 12G-SDI I/O is carried on SFP cages (SDI SFP modules)
      port("SDI In 1 (SFP)", "sdi", "input", "sfp"),
      port("SDI In 2 (SFP)", "sdi", "input", "sfp"),
      port("SDI Out 1 (SFP)", "sdi", "output", "sfp"),
      port("SDI Out 2 (SFP)", "sdi", "output", "sfp"),
      port("Audio In", "analog-audio", "input", "phoenix"),
      port("Audio Out", "analog-audio", "output", "phoenix"),
      port("S/PDIF Out 1", "spdif", "output"),
      port("S/PDIF Out 2", "spdif", "output"),
      port("Control (OOB)", "ethernet", "bidirectional"),
      port("SFP+ 1 (Transport)", "ethernet", "bidirectional", "sfp"),
      port("SFP+ 2 (Transport)", "ethernet", "bidirectional", "sfp"),
      port("DC Power (12V)", "power", "input", "barrel"),
    ],
  },
  // Evertz NUC-AV-100 — NUCLEUS Session Manager appliance (client package import)
  {
    id: "c0a80101-0363-4000-8000-000000000821",
    deviceType: "computer",
    label: "Evertz NUC-AV-100",
    manufacturer: "Evertz",
    modelNumber: "NUC-AV-100",
    referenceUrl: "https://av.evertz.com/av-solutions/by-product/nucleus-platform/session-manager/",
    searchTerms: ["evertz", "nucleus", "session manager", "nuc", "av-100", "management", "controller"],
    rackForm: "shelf-only",
    ports: [
      port("HDMI Out", "hdmi", "output"),
      port("DP Out", "displayport", "output"),
      port("VGA Out", "vga", "output"),
      port("USB 1", "usb", "bidirectional", "usb-a"),
      port("USB 2", "usb", "bidirectional", "usb-a"),
      port("LAN 1", "ethernet", "bidirectional"),
      port("LAN 2", "ethernet", "bidirectional"),
      port("DC Power", "power", "input", "barrel"),
    ],
  },
  // Cisco Catalyst C9300-48UXM-A — 48-port mGig UPOE (client package import; drawing-derived)
  {
    id: "c0a80101-0375-4000-8000-000000000839",
    deviceType: "network-switch",
    label: "Cisco C9300-48UXM-A",
    manufacturer: "Cisco",
    modelNumber: "C9300-48UXM-A",
    referenceUrl: "https://www.cisco.com/site/us/en/products/networking/switches/catalyst-9300-series-switches/index.html",
    searchTerms: ["cisco", "catalyst", "c9300", "48uxm", "switch", "upoe", "mgig", "managed"],
    poeBudgetW: 822, // UPOE budget with 1100 W PSU
    voltage: "100-240V",
    rackForm: "full",
    ports: [
      ...ports("PoE Port", "ethernet", "bidirectional", 48),
      port("10GE Port 49", "ethernet", "bidirectional"),
      port("10GE Port 50", "ethernet", "bidirectional"),
      port("SFP Port 51", "ethernet", "bidirectional", "sfp"),
      port("SFP Port 52", "ethernet", "bidirectional", "sfp"),
      port("Mgmt", "ethernet", "bidirectional"),
      port("Console (RJ45)", "serial", "bidirectional", "rj45"),
      port("AC Power 1", "power", "input"),
      port("AC Power 2", "power", "input"),
    ],
  },
  // Cisco SG350-10 — 10-port GbE managed (client package import; drawing-derived)
  {
    id: "c0a80101-0376-4000-8000-000000000840",
    deviceType: "network-switch",
    label: "Cisco SG350-10",
    manufacturer: "Cisco",
    modelNumber: "SG350-10",
    referenceUrl: "https://www.cisco.com/c/en/us/support/switches/sg350-10-10-port-gigabit-managed-switch/model.html",
    searchTerms: ["cisco", "sg350", "switch", "10 port", "gigabit", "managed"],
    rackForm: "shelf-only",
    ports: [
      ...ports("Port", "ethernet", "bidirectional", 8),
      port("Port 9 (Combo)", "ethernet", "bidirectional"),
      port("Port 10 (Combo)", "ethernet", "bidirectional"),
      port("DC Power", "power", "input", "barrel"),
    ],
  },
];
